version: "3.3"
services:
  app:
    build: ./app
    links:
      - mysql-db
    ports: 
      - "5000:5000"

  mysql-db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: