DATABASE:
  user:
    type: mysql
    host: sql12.freemysqlhosting.net
    username: sql12613695
    password: lqdLFIXHtD
    port: 3306
    database: sql12613695
  binds:
    user:
      type: mysql
      host: sql12.freemysqlhosting.net
      username: sql12613695
      password: lqdLFIXHtD
      port: 3306
      database: sql12613695
    app_meta:
      type: mysql
      host: sql12.freemysqlhosting.net
      username: sql12613695
      password: IqdLFIXHtD
      port: 3306
      database: sql12613695

DEBUG: True

SECRET_KEY: secret_key_123

SQLALCHEMY_TRACK_MODIFICATIONS: True

TESTING: True

