DATABASE:
  app_auth:
    type: mysql
    host: 127.0.0.1
    username: root
    password: password
    port: 3306
    database: app_auth
  binds:
    # app_auth:
    #   type: mysql
    #   host: 127.0.0.1
    #   username: root
    #   password: password
    #   port: 3306
    #   database: app_auth
    app_meta:
      type: mysql
      host: 127.0.0.1
      username: root
      password: password
      port: 3306
      database: app_meta

# Server: sql12.freemysqlhosting.net
# Name: sql12616687
# Username: sql12616687
# Password: 7kY2mMKwbm
# Port number: 3306

DEBUG: True
PROPAGATE_EXCEPTIONS: True

# Database: starter_kit
# Username: root_user_9634


SECRET_KEY: \xf9'\xe4p(\xa9\x12\x1a!\x94\x8d\x1c\x99l\xc7\xb7e\xc7c\x86\x02MJ\xa0

SQLALCHEMY_TRACK_MODIFICATIONS: True

TESTING: True

