DATABASE:
  user:
    type: mysql
    host: sql12.freemysqlhosting.net
    username: sql12612529
    password: TZuKC2mhtc
    port: 3306
    database: sql12612529
  app_meta:
    type: mysql
    host: sql12.freemysqlhosting.net
    username: sql12612529
    password: TZuKC2mhtc
    port: 3306
    database: sql12612529

DEBUG: True

SECRET_KEY: secret_key_123

SQLALCHEMY_TRACK_MODIFICATIONS: True

TESTING: True

