DATABASE:
  starter_kit:
    type: mysql
    host: 127.0.0.1
    username: root
    password: password
    port: 3306
    database: starter_kit
  # binds:
  #   starter_kit:
  #     type: mysql
  #     host: 127.0.0.1
  #     username: root
  #     password: password
  #     port: 3306
  #     database: starter_kit
  #   app_meta:
  #     type: mysql
  #     host: 127.0.0.1
  #     username: root
  #     password: password
  #     port: 3306
  #     database: starter_kit

DEBUG: True
PROPAGATE_EXCEPTIONS: True


SECRET_KEY: \xf9'\xe4p(\xa9\x12\x1a!\x94\x8d\x1c\x99l\xc7\xb7e\xc7c\x86\x02MJ\xa0

SQLALCHEMY_TRACK_MODIFICATIONS: True

TESTING: True

