DATABASE:
  app_auth:
    type: mysql
    host: 127.0.0.1
    username: root
    password: password
    port: 3306
    database: app_auth_test
  binds:
    app_auth:
      type: mysql
      host: 127.0.0.1
      username: root
      password: password
      port: 3306
      database: app_auth_test
    app_meta:
      type: mysql
      host: 127.0.0.1
      username: root
      password: password
      port: 3306
      database: app_meta_test

DEBUG: True
PROPAGATE_EXCEPTIONS: False


SECRET_KEY: \xf9'\xe4p(\xa9\x12\x1a!\x94\x8d\x1c\x99l\xc7\xb7e\xc7c\x86\x02MJ\xa1

SQLALCHEMY_TRACK_MODIFICATIONS: True

TESTING: True

